name: Build, upload, and publish Arch Linux package
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
        buildah from --name ctnr archlinux
        buildah run ctnr pacman --noconfirm -Syu
        buildah run ctnr pacman --noconfirm -S --needed base-devel

        buildah run ctnr useradd -m dev
        buildah run ctnr sh -c 'printf "%s\n" "dev ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers.d/dev'

        buildah copy --chown dev ctnr telegram-desktop-userfonts /home/dev/telegram-desktop-userfonts

        buildah config -u dev --workingdir /home/dev/telegram-desktop-userfonts ctnr
        buildah commit --rm ctnr img

        podman run --name ctnr img makepkg --noconfirm -s

        pkg="$(podman exec ctnr sh -c "printf '%s\n' telegram-desktop-userfonts-*-x86_64.pkg.tar.xz")"
        podman cp ctnr:/home/dev/telegram-desktop-userfonts/$pkg ./
      - uses: actions/upload-artifact@v2
        with:
          name: telegram-desktop-x86_64
          path: telegram-desktop-userfonts-*-x86_64.pkg.tar.xz
