name: Build, upload, and publish Arch Linux package
on:
  push:
    tags:
      - '[0-9]*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:

      - name: prepare build environment
        run: |
          pacman-key --init
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Su --noconfirm
          pacman -S --noconfirm pacman-contrib sudo docker git cmake extra-cmake-modules ninja meson boost qt6-base
          echo "nobody ALL=(ALL) NOPASSWD: /usr/bin/pacman" | tee -a /etc/sudoers

      - name: clean up some space
        run: |
          df -a /
          paccache -rk0
          docker image prune --all --force || true
          rm -rf /__t/*
          df -a /

      - name: build package
        env:
          AWK_PKGBUILD: |
            # turn off too verbose cmake output
            /DCMAKE_VERBOSE_MAKEFILE/ { next }
            { print }
        run: |
          git clone https://aur.archlinux.org/telegram-desktop-userfonts.git .
          echo "${AWK_PKGBUILD}" | awk -f - PKGBUILD > PKGBUILD.ci
          chown -R nobody .
          runuser -u nobody -- makepkg --syncdeps --noconfirm --cleanbuild -p PKGBUILD.ci

      - name: list built packages
        run: |
          echo "PKG=$(ls telegram-desktop-userfonts-[0-9]*.pkg.*)" | tee -a $GITHUB_ENV

      - name: preserve artifcats
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG }}
          path: ${{ env.PKG }}

      - name: create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.PKG }}
